ALTER TABLE users
ADD COLUMN IF NOT EXISTS personal_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS company_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS invite_status VARCHAR(20),
ADD COLUMN IF NOT EXISTS invite_token VARCHAR(120),
ADD COLUMN IF NOT EXISTS invite_expires_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS invite_used_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS invited_by INTEGER REFERENCES users(user_id),
ADD COLUMN IF NOT EXISTS invited_at TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS users_invite_token_unique
ON users(invite_token)
WHERE invite_token IS NOT NULL;
